name: Node.js CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master ]

jobs:
  build:
    runs-on: self-hosted

steps:
  - uses: actions/checkout@v2
  - names: Use Node.js ${{ matrix.node-versions }}
    uses: actions/setup-node@v2
    with: 
      node-version: ${{matrix.node-version}}
  - run: |
      npm i
      npm run build
